{% set name = "suitcase-msgpack" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f846a7b63ae2d7676787f5269ca2bdd3c33532fc80608499c696752628cd4e5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - event-model >=1.8.0
    - msgpack-python
    - msgpack-numpy
    - python >=3.6
    - suitcase-utils

test:
  imports:
    - suitcase.msgpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/suitcase-msgpack/
  summary: This is a suitcase subpackage for writing msgpack.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CJ-Wright
